# https://dart.dev/tools/pub/pubspec
name: flutter_tilt
description: Easily apply tilt parallax hover effects for Flutter, which supports tilt, light, shadow effects, and many custom parameters.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://semver.org/spec/v2.0.0-rc.1.html
# https://dart.dev/tools/pub/versioning#semantic-versions
# https://dart.dev/tools/pub/dependencies#version-constraints
version: 0.0.7
repository: https://github.com/AmosHuKe/flutter_tilt
issue_tracker: https://github.com/AmosHuKe/flutter_tilt/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

topics:
  - tilt
  - skew
  - parallax
  - hover
  - widget

screenshots:
  - description: 'Example Preview GIF'
    path: README/preview2-small.gif
  - description: 'Example Preview GIF'
    path: README/preview-small.gif