name: "How to use"
description: "How to use the flutter_tilt"
title: "[How to use] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
        You need read document before you ask question.
        If you can, 

        - Search the issue list.
        - Check out the [Live Demo](https://amoshuke.github.io/flutter_tilt_book).
        - Browser search.

        to see if someone has asked the same question.
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: Check all that apply
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "e.g. I want to disable the sensors."
    validations:
      required: true
  - type: textarea
    id: my-code
    attributes:
      label: My code
      description: "I want to know how to use the method."
    validations:
      required: false
  - type: textarea
    id: try-do-it
    attributes:
      label: Try do it
      description: "I have tried to do it, but I don't know how to do it."
      placeholder: |
        e.g. I tried to configure disable=true, but it doesn't work.
    validations:
      required: false
