name: "test coverage"
run-name: "Test Coverage"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "example/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "example/**"

jobs:
  test_minimum_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.0'
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Test
        run: flutter test
  test_latest_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.0.0'
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Test Coverage
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
